### ISSUE TITLE
Error in which(tree$edge[, 1] == node)

### ISSUE THREAD

**Issue by pelow22** [ivanlfm/BGB_BSM_multiple_trees#3]
Dear Ivan,

I have tried another dataset and I got this error below. 
Folders were populated only by "rep1".

It seems something related to the fact that the phylogenies have extinct (fossil) tips, but I could not figure it out.

I would really appreciate if you could help me out.
Thank you in advance,
Peter

Error in which(tree$edge[, 1] == node) : 
  'list' object cannot be coerced to type 'integer'
Além disso: Warning message:
In (function (npt = min(n + 2L, 2L * n), rhobeg = NA, rhoend = NA,  :
  unused control arguments ignored
Called from: which(tree$edge[, 1] == node)
Browse[1]> 

Dataset and logs:
[Para_Ivan_set_2021.zip](https://github.com/ivanlfm/BGB_BSM_multiple_trees/files/7254567/Para_Ivan_set_2021.zip)

**Comment by ivanlfm** [comment]
Hi Pedro -- thanks for letting me know, and for the files. I will look into this!

**Comment by ivanlfm** [comment]
Hi Pedro -- the issue was with the "nodes of interest" option. If you don't want to tag the nodes of interest in the output table, instead of

`nodes_of_interest <- list( c("") )`

use

`nodes_of_interest <- list( )`

Using the former option, the code treats the empty vector as a node of interest, but since it has no taxa, it fails to parse the results correctly. By using the second option, nodes_of_interest has 0 length and thus this step is skipped (the code only tries of tag nodes of interest if the list has a length greater than 0). Perhaps I should add a switch for this ("tag_nodes_of_interest <- TRUE") instead of checking the length of the vector?

Also, a minor unrelated issue: n_stochastic_maps needs to be equal to, or larger than, n_maps_count_LTT or the code will fail. I'll add a check to fix this automatically in the next version.

Best,
Ivan
