### ISSUE TITLE
"returning Inf" error

### ISSUE THREAD

**Issue by cskema** [ivanlfm/BGB_BSM_multiple_trees#4]
Hi,

I'm trying to run your R code for using multiple trees in BioGeoBEARS and BSM analyses. I keep getting this error:

     Error in file(con, "r") : cannot open the connection
     In addition: Warning messages:
     1: In min(which(time_slices > current_height)) :
         no non-missing arguments to min; returning Inf
     2: In file(con, "r") :
         cannot open file '1k_try01/modifier_matrices/Inf_timeperiods_Sthel.txt': No such file or directory

In an attempt to better understand what the underlying problem was, I analyzed (one by one) a subsample of the first 15 of my posterior trees and found that 5 of 15 of them throw this message, while the other 10 were analyzed with no problems.

Have you seen anything like this before? Would you have any idea what characteristics of these trees might be problematic? Any insights would be appreciated!

Thanks!

**Comment by ivanlfm** [comment]
Hello, thanks for pointing this. This error happens because `current_height` (the oldest age of the current tree) is larger than the oldest time slice (as taken from your input file). This may happen if you set the age of the last slice with the consensus tree in mind, but some of the trees from the posterior distribution are older than the consensus. To fix this, simply re-set the age of the oldest time slice to an age older than that of the oldest tree in the sample (or an arbitrarily large value, e.g. 999). This is because BioGeoBEARS requires the last time slice to be older than the height of your tree.
