### ISSUE TITLE
Regarding getting the average number of transitions between ranges from the stochastic maps 

### ISSUE THREAD

**Issue by abhitims** [ivanlfm/BGB_BSM_multiple_trees#7]
Hi Ivan,

Many thanks for putting out the code, it's really great! Quick question, I was interested in getting the average number of transitions between states and then summarize them wrt the events. I have been trying to summarise them as follows:
BSM_transitions %>% group_by(ageStart,rangeAncestor,rangeStart, transitionCladogType) %>%  summarise(...)

However, I was checking your code again, and in line 921 onwards, I was curious why not count the events based on the entries in the column transitionCladogType in the datafarame BSM_transitions,? As opposed to checking the ancestor range and range start states and then populating the state and event table 

Apologies, if I am missing something obvious here, but any feedback will be much appreciated.

Thanks for your time.

Regards,
Abhishek

**Comment by ivanlfm** [comment]
Hi Abhishek,

You are not missing anything, and what you propose makes sense -- it may be useful to extract transitions directly from the BSM table, rather than as the transition between the states present in consecutive nodes.

When we first wrote the code, we were more interested in a "tree-focused" approach, recording only the transitions between states of the nodes. Of course, because in BioGeoBEARS the transitions are probabilistic, there may be many transitions along a branch that are currently not being summarized by my code. For most situations, this will not be a big issue because, for many (most?) branches in regular situations, these "extra" transitions may be rare. 
However, in some situations, they may differ greatly. I noticed this a few months ago, when I summarized transitions in the same tree in two different scenarios (unconstrained vs. some dispersal events only allowed in one of the time slices). The second scenario implies a much higher dispersal rate parameter and thus "extra' dispersal events along branches become much more common. So if you want to directly compare the number of dispersal events, perhaps it would be best to extract these numbers from the BSM table.

Ideally I should modify the code to implement this (perhaps with two different summary tables -- one as currently implemented, and the other extracting the transitions from the BSM table), but I cannot write this right now -- perhaps in a few weeks. Of course, if it is something straightforward to you, please feel free to pull the code and modify it to your needs.

Best,
Ivan

**Comment by abhitims** [comment]
Thanks for the prompt reply Ivan, much appreciated. And thanks, that definitely allays some concerns on my end, if I had overlooked something. Yes, I do get in some cases a "tree-based" approach would be more appropriate. 

If you have time here are two chunks I have used to summarise the events. The key being for cladogentic events the summaries being from rangeAncestor and rangeStart and for anagenetic events it being from rangeStart and rangeEnd, and then for both summarising based on rangeStart. Is that correct? 

Here is how I have summarised the cladogenetic and anagenetic events and the output matches the 
"state_by_state_transitions_average_BSM" output.

**Case 1: Overall summary**
```
rbind(
       #Cladogenetic events
        BSM_transitions %>% group_by(rangeAncestor,rangeStart,transitionCladogType) %>% 
        summarise(count=n()) %>% rename("From"=rangeAncestor,"To"=rangeStart) %>% 
        rename(events=transitionCladogType),
        
        #Anagenetic events
        BSM_transitions %>% group_by(rangeStart,rangeEnd,transitionAnagType) %>% 
        summarise(count=n()) %>%  filter(transitionAnagType=="dispersal") %>% 
        rename("From"=rangeStart,"To"=rangeEnd) %>% 
        rename(events=transitionAnagType)) %>%   #Joining both anagenetic and cladogenetic events
        
        group_by(From,To) %>% summarise(count=sum(count)) %>% 
        mutate(prop=count/(20*1000)) %>%  #20 BSMs and 1000 trees
        select(-count) %>% 
        filter(prop>0) %>% 
        pivot_wider(names_from = To,values_from = prop,values_fill = 0) %>%
        as.data.frame()
```


However, I wanted to summarise all events for each state for each time bin, so I have summarised the events from the BSM_transition table as follows:

**Case 2: Summary per state and time bin**
```

BSM_summary_clado <-   BSM_transitions %>% 
                                         group_by(ageStart, bins,   nodeStart,nodeEnd,rangeAncestor,rangeStart, transitionCladogType)%>%
                                         summarise(occ=n())  %>%
                                         group_by(bins,rangeStart,transitionCladogType) %>%
                                         summarise(tot_events=sum(occ),   average_events=mean(occ),
                                         upper_quant=quantile(occ,probs = 0.95), lower_quant=quantile(occ,probs = 0.05)) %>% 
                                         rename(Event=transitionCladogType)
#Here summarising wrt rangeAncestor and rangeStart for cladogenetic events
BSM_summary_anag <-   BSM_transitions %>% 
                                         group_by(ageStart, bins,nodeStart,nodeEnd, rangeStart,rangeEnd,  transitionAnagType) %>% 
                                         summarise(occ=n()) %>% filter(transitionAnagType!="–") %>%  
                                         group_by(bins,rangeStart,transitionAnagType) %>%
                                         summarise(tot_events=sum(occ),
                                         average_events=mean(occ),
                                         upper_quant=quantile(occ,probs = 0.95),
                                         lower_quant=quantile(occ,probs = 0.05)) %>% rename(Event=transitionAnagType))
 #Here summarising wrt rangeStart and rangeEnd for Anagenetic events
 

BSM_Clado_Ano_state.final <-   rbind(BSM_summary_clado, BSM_summary_anag )
```

Please let me know if this works or makes sense to you if you have time.

Thank you.

Have a nice day!

Abhishek

**Comment by ivanlfm** [comment]
Hi Abhishek,

I find it difficult to evaluate the code without running it myself and checking if it provides the desired output.
However, I noticed that you are re-summarizing events from the table BSM_transitions. This table is already "filtered" for the tree-based approach.

If you want to count all the events, as discussed in the original post, you should parse the BSM outputs from BioGeoBEARS (objects RES_clado_events_tables and RES_ana_events_tables). Please note that if you have 100 trees and 10 stochastic maps, you will have 1000 versions of each of these tables, so you need to code a loop to parse  all of them.

It may be useful to check (or modify) the section of the code "get the transitions and their ages from stochastic mapping" (line 730).

Best,
Ivan

**Comment by abhitims** [comment]
Thanks Ivan, yeah I suspected that, but wasn't sure. Sure I will do that. Thanks much for your time and best wishes for the new year.

Warmly,
Abhishek
